# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Chris Sharkey's Website
tagline:          'Blog'
description:      ''
url:              http://www.chrissharkey.com
baseurl:          /

author:
  name:           'Chris Sharkey'
  url:            https://twitter.com/chrissharkey

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chrissharkey/chrissharkey.github.io
